### PR TITLE
Replaces less with scss

### PR DESCRIPTION
**Pull request by zrpnr**
Remove less and replace with gulp-sass per https://github.com/AtenDesignGroup/stylizer-front-end/issues/6

### CODE REVIEW

**Comment by zrpnr** [comment]
Github is saying there are merge conflicts but I've tested locally and not had problems... let me know if I need to make any edits.

**Comment by pixelwhip** [comment]
There are conflicts in the debug folder. This is what I get when trying to merge into master.

```
stylizer-front-end|master ⇒ git checkout -b test
Switched to a new branch 'test'
stylizer-front-end|test ⇒ git merge origin/6-less-scss
Removing gulp/tasks/less.js
CONFLICT (modify/delete): debug/css/maps/main.css.map deleted in origin/6-less-scss and modified in HEAD. Version HEAD of debug/css/maps/main.css.map left in tree.
Auto-merging debug/css/main.css
CONFLICT (content): Merge conflict in debug/css/main.css
Auto-merging app/sass/_typography.scss
Auto-merging app/sass/_pattern.scss
Auto-merging app/sass/_base.scss
Removing app/less/variables.less
Removing app/less/mixins.less
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by zrpnr** [comment]
I restored the debug css files from master, those will get overwritten when you run gulp. Now when I follow the merge conflict instructions it's working but still says conflicts must be resolved.

**Comment by zrpnr** [comment]
I just removed the commits that had the generated css. Should be ok now, I've tested locally several times and I never get merge conflicts now. Could be I force-pushed too many times :$

**Comment by zrpnr** [comment]
It was because I had branched off master before you committed some work, should be good now!

**Comment by pixelwhip** [comment]
@zrpnr Yep, that fixed. I tested and it works!

**Pull request merged**
